paths:
  /comments/{postId}:
    get:
      summary: Get comments by Post ID
      description: Retrieve all comments associated with a specific post
      tags: 
        - Comments
      security:
        - accessTokenAuth: [] 
      parameters:
        - name: postId
          in: path
          required: true
          description: The ID of the post
          schema:
            type: string
      responses:
        200:
          description: List of comments successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        500:
          description: Server error when retrieving comments

    post:
      summary: Create a comment
      description: Add a new comment to a post
      tags: 
        - Comments
      security:
        - accessTokenAuth: [] 
      parameters:
        - name: postId
          in: path
          required: true
          description: The ID of the post
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The content of the comment
      responses:
        201:
          description: Comment successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        400:
          description: Bad request, invalid or missing parameters
        500:
          description: Server error when creating comment

components:
  securitySchemes:
    accessTokenAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    Comment:
      type: object
      properties:
        authorId:
          type: string
          description: ID of the author who wrote the comment
        content:
          type: string
          description: Content of the comment
        date:
          type: string
          format: date-time
          description: Date when the comment was created
        postId:
          type: string
          description: ID of the post that this comment belongs to

