/users/register:
  post:
    summary: Register a new user
    tags: [Users]
    requestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              name:
                type: string
              image:
                type: string
                format: binary
    responses:
      201:
        description: User created successfully
      400:
        description: Email already exists
      500:
        description: Server error